# Generated by Django 5.0.6 on 2024-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_image', models.ImageField(blank=True, upload_to='images/')),
                ('pro_title', models.TextField(max_length=200)),
                ('pro_price', models.TextField(max_length=200)),
            ],
        ),
    ]
