# Generated by Django 5.0.7 on 2024-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxfashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jel_item', models.TextField(max_length=100)),
                ('jel_rate', models.TextField(max_length=100)),
                ('jel_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
