# Generated by Django 5.0.7 on 2024-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxfashion', '0002_jewellery_delete_products copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField(max_length=1)),
                ('Lastname', models.TextField(max_length=1)),
                ('Emailaddress', models.TextField(max_length=1)),
                ('phonenumber', models.TextField(max_length=1)),
                ('Addressline1', models.TextField(max_length=200)),
                ('Addressline2', models.TextField(max_length=200)),
                ('country', models.TextField(max_length=1)),
                ('region', models.TextField(max_length=1)),
                ('placeholder', models.TextField(max_length=1)),
            ],
        ),
    ]
