# Generated by Django 5.0.7 on 2024-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxfashion', '0003_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Emailaddress',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Firstname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Lastname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phonenumber',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='placeholder',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='region',
            field=models.TextField(max_length=50),
        ),
    ]
