# Generated by Django 5.0.7 on 2024-08-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxfashion', '0004_alter_checkout_emailaddress_alter_checkout_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='placeholder',
        ),
    ]
