# Generated by Django 5.0.7 on 2024-08-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxfashion', '0005_remove_checkout_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='region',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
